-- INSERIR UM REGISTRO
INSERT INTO TB_IP_PRODUTO (titulo, preco_compra, preco_venda)
VALUES ('Mochila Da Disney', '100', '123');

-- BUSCAR REGISTROS
SELECT * FROM TB_IP_PRODUTO;

-- REMOVENDO TABELA
DROP TABLE TB_IP_PRODUTO;

-- APAGAR DADOS DA TABELA
TRUNCATE TABLE TB_IP_PRODUTO;

-- CRIAR TABELA
CREATE TABLE TB_IP_PRODUTO(
    produto_id INT IDENTITY,
    titulo VARCHAR(255),
    preco_compra DECIMAL(8,2) NOT NULL,
    preco_venda  DECIMAL(8,2) DEFAULT 0,
    desconto INT,
    cor  VARCHAR(255),
    categoria VARCHAR(255),
    data_entrada DATETIME,
    data_saida DATETIME,
    quantidade INT,
    tamanho VARCHAR(255),
    foto VARCHAR(255),
    forma_de_pagamento VARCHAR(255),
    observacao  VARCHAR(255),
    marca  VARCHAR(255),
    origem  VARCHAR(255)
)

-- ALTERAR UMA COLUNA(DEFININDO VALOR PADRAO)
ALTER TABLE TB_IP_PRODUTO
ADD DEFAULT 0 FOR DESCONTO;

-- ALTERAR COLUNA(DEFININDO CHAVE PRIMARIA)
ALTER TABLE TB_IP_PRODUTO 
ADD CONSTRAINT PK_TB_IP_PRODUTO 
PRIMARY KEY (produto_id)

-- BUSCAR INFORMACOES SOBRE A TABELA
EXEC sp_help TB_IP_PRODUTO
